name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: build-test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target

      - name: Show toolchain
        run: rustc -Vv && cargo -V

      - name: Clippy (deny warnings)
        run: cargo clippy --all-targets -- -D warnings

      - name: Run tests (capture log)
        shell: bash
        run: |
          set -euo pipefail
          cargo test --verbose 2>&1 | tee test-output.txt

      - name: Flaky-test guard (re-run tests; must pass twice)
        shell: bash
        run: |
          set -euo pipefail
          cargo test --verbose 2>&1 | tee -a test-output.txt

      - name: Upload test log (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-log-${{ matrix.os }}
          path: test-output.txt

  coverage:
    name: coverage (ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin --locked

      - name: Generate coverage (tarpaulin)
        run: |
          cargo tarpaulin --workspace --out Lcov --out Html --timeout 180 --engine llvm --ignore-tests
          ls -la
        env:
          RUSTFLAGS: -Cinstrument-coverage

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            tarpaulin-report.html
            lcov.info


