name: GUI QA & CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  gui-smoke:
    name: gui-smoke (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target

      - name: Build
        run: cargo build

      - name: Run GUI API smoke
        run: cargo test --test gui_api_smoke -- --nocapture

      - name: Run Messaging UI watcher tests
        run: cargo test --test messaging_ui_watcher_tests -- --nocapture

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gui-failure-artifacts-${{ runner.os }}
          path: |
            target/debug/deps/**/*.d
            target/debug/deps/**/*.pdb
            target/debug/deps/**/*.dSYM
            target/debug/**/*.log
          if-no-files-found: ignore


