name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    name: build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target

      - name: Build release
        run: cargo build --release

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: pigeon-${{ runner.os }}
          path: |
            target/release/*pigeon* 
            target/release/*secure* 

  publish:
    name: publish GitHub Release
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


