name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            Pigeon -> target

      - name: Cargo fmt check
        working-directory: Pigeon
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        working-directory: Pigeon
        run: cargo clippy --all-targets -- -D warnings

      - name: Cargo test
        working-directory: Pigeon
        run: cargo test --verbose


